# Generated by Django 5.1.15 on 2026-07-08 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0061_task_assignee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='Reviewer note, e.g. rejection reason', null=True, verbose_name='review note'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Task review status: pending / approved / rejected', max_length=16, verbose_name='review status'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the task was last reviewed', null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Reviewer who last approved/rejected this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
