# Generated by Django 5.1.15 on 2026-07-08 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_task_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reopened', 'Reopened')], help_text='Review transition action', max_length=32)),
                ('note', models.TextField(blank=True, default='', help_text='Reviewer note, e.g. rejection reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('actor', models.ForeignKey(help_text='Actor User ID', on_delete=django.db.models.deletion.CASCADE, related_name='task_review_history', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Task ID', on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='tasks.task')),
            ],
            options={
                'db_table': 'task_review_history',
            },
        ),
    ]
