# Generated by Django 5.1.15 on 2026-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0064_backfill_review_status_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('first_approved', '1차 승인'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Task review status: pending / approved / rejected', max_length=16, verbose_name='review status'),
        ),
        migrations.AlterField(
            model_name='taskreviewhistory',
            name='action',
            field=models.CharField(choices=[('first_approved', 'First approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reopened', 'Reopened')], help_text='Review transition action', max_length=32),
        ),
    ]
