# Generated by Django 5.1.15 on 2026-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0066_task_review_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreviewhistory',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('fp', '오탐(없는 이벤트 라벨) FP'), ('fn', '미탐(이벤트 누락) FN'), ('boundary', '경계·박스 불량'), ('wrong_class', '클래스 오류'), ('timestamp', '타임스탬프 오차'), ('guideline', '지침 위반'), ('other', '기타')], default=None, help_text='Structured rejection reason (Error Class); null for approvals and pre-adoption history', max_length=32, null=True),
        ),
    ]
