# Generated by Django 5.1.15 on 2026-07-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0067_taskreviewhistory_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='active_seconds',
            field=models.FloatField(default=None, help_text='Active (mouse/keyboard) work time in seconds; excludes idle gaps of 60s or longer', null=True, verbose_name='active seconds'),
        ),
    ]
