run_storage:
  module: dagster._core.storage.runs
  class: SqliteRunStorage
  config:
    base_dir: /app/dagster_home/storage

run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 4
    tag_concurrency_limits:
      - key: duckdb_writer
        value: "true"
        limit: 1
      - key: duckdb_raw_writer
        value: "true"
        limit: 1
      - key: duckdb_label_writer
        value: "true"
        limit: 1
      - key: duckdb_yolo_writer
        value: "true"
        limit: 1

event_log_storage:
  module: dagster._core.storage.event_log
  class: SqliteEventLogStorage
  config:
    base_dir: /app/dagster_home/storage

schedule_storage:
  module: dagster._core.storage.schedules
  class: SqliteScheduleStorage
  config:
    base_dir: /app/dagster_home/storage

local_artifact_storage:
  module: dagster._core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /app/dagster_home/storage
