# Generated by Django 5.1.15 on 2026-07-03 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_project_annotator_evaluation_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Whether this project has been submitted (self-contained F1).', verbose_name='is submitted'),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_at',
            field=models.DateTimeField(default=None, help_text='Timestamp of the first submit.', null=True, verbose_name='submitted at'),
        ),
        migrations.CreateModel(
            name='LabelStateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted')], help_text='Transition action', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('actor', models.ForeignKey(help_text='Actor User ID', on_delete=django.db.models.deletion.CASCADE, related_name='label_state_history', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project ID', on_delete=django.db.models.deletion.CASCADE, related_name='label_state_history', to='projects.project')),
            ],
            options={
                'db_table': 'label_state_history',
            },
        ),
    ]
