# Generated by Django 5.1.15 on 2026-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_project_is_submitted_project_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelstatehistory',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional note (e.g. rejection reason)', null=True),
        ),
        migrations.AlterField(
            model_name='labelstatehistory',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('rejected', 'Rejected')], help_text='Transition action', max_length=32),
        ),
    ]
