# Generated by Django 5.1.15 on 2026-07-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('labeler', 'Labeler'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='reviewer', help_text='Role of the member within the organization', max_length=16),
        ),
    ]
