# Generated by Django 5.1.15 on 2026-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('labeler', 'Labeler'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='labeler', help_text='Role of the member within the organization', max_length=16),
        ),
    ]
